name: HOnStar MQTT
version: "1.5.4"
slug: honstar-mqtt
description: >-
  MQTT Bridge for Honda/Acura EVs based on the GM BEV3 platform.
  Polls vehicle status (battery, range, tires, charging, odometer)
  and publishes to MQTT topics.
url: https://github.com/tsightler/honstar-mqtt
arch:
  - amd64
  - aarch64
  - armv7
  - armhf
startup: application
boot: auto
services:
  - mqtt:need
options:
  hws_email: ""
  hws_password: ""
  hws_pin: ""
  vin: ""
  mqtt_url: "mqtt://auto_username:auto_password@auto_hostname"
  poll_interval: 900
  debug: false
schema:
  hws_email: email
  hws_password: password
  hws_pin: str?
  vin: str?
  mqtt_url: str?
  poll_interval: int?
  debug: bool?
image: ghcr.io/tsightler/honstar-mqtt-{arch}
init: false
